import { defineProperties } from '@vanilla-extract/sprinkles'
import { basicNumberSize, basicPercentageSize, breakPoint, responsiveConditions } from './utils'

export const basicScreenSize = {
  '3xs': '256px',
  '2xs': '288px',
  'xs': '320px',
  'sm': '384px',
  'md': '448px',
  'lg': '512px',
  'xl': '576px',
  '2xl': '672px',
  '3xl': '768px',
  '4xl': '896px',
  '5xl': '1024px',
  '6xl': '1152px',
  '7xl': '1280px',
}

export const sizingProperties = defineProperties({
  conditions: responsiveConditions,
  defaultCondition: 'default',
  properties: {
    width: {
      ...basicNumberSize,
      ...basicPercentageSize,
      screen: '100vw',
      min: 'min-content',
      max: 'max-content',
      fit: 'fit-content',
    },
    minWidth: {
      0: '0px',
      full: '100%',
      min: 'min-content',
      max: 'max-content',
      fit: 'fit-content',
    },
    maxWidth: {
      0: '0px',
      ...basicScreenSize,
      none: 'none',
      full: '100%',
      min: 'min-content',
      max: 'max-content',
      fit: 'fit-content',
      prose: '65ch',
      screenSM: breakPoint.sm,
      screenMD: breakPoint.md,
      screenLG: breakPoint.lg,
      screenXL: breakPoint.xl,
      screen2XL: breakPoint['2xl'],
    },
    height: {
      ...basicNumberSize,
      ...basicPercentageSize,
      screen: '100vh',
      min: 'min-content',
      max: 'max-content',
      fit: 'fit-content',
    },
    minHeight: {
      0: '0px',
      full: '100%',
      screen: '100vh',
      min: 'min-content',
      max: 'max-content',
      fit: 'fit-content',
    },
    maxHeight: {
      0: '0px',
      ...basicScreenSize,
      none: 'none',
      full: '100%',
      screen: '100vh',
      min: 'min-content',
      max: 'max-content',
      fit: 'fit-content',
    },
  },
  shorthands: {
    w: ['width'],
    minW: ['minWidth'],
    maxW: ['maxWidth'],
    h: ['height'],
    minH: ['minHeight'],
    maxH: ['maxHeight'],
  },
})
