import { defineProperties } from '@vanilla-extract/sprinkles'
import { palette } from './color.css'
import { basicNumberSize, responsiveConditions } from './utils'

export const typographyProperties = defineProperties({
  conditions: responsiveConditions,
  defaultCondition: 'default',
  properties: {
    fontFamily: {
      sans: 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
      serif: 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
      mono: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    },
    fontSize: {
      'xs': '12px',
      'sm': '14px',
      'base': '16px',
      'lg': '18px',
      'xl': '20px',
      '2xl': '24px',
      '3xl': '30px',
      '4xl': '36px',
      '5xl': '48px',
      '6xl': '60px',
      '7xl': '72px',
      '8xl': '96px',
      '9xl': '128px',
    },
    lineHeight: {
      'xs': '16px',
      'sm': '20px',
      'base': '24px',
      'lg': '28px',
      'xl': '28px',
      '2xl': '32px',
      '3xl': '36px',
      '4xl': '40px',
      '5xl': 1,
      '6xl': 1,
      '7xl': 1,
      '8xl': 1,
      '9xl': 1,
      '3': '12px',
      '4': '16px',
      '5': '20px',
      '6': '24px',
      '7': '28px',
      '8': '32px',
      '9': '36px',
      '10': '40px',
      'none': 1,
      'tight': 1.25,
      'snug': 1.375,
      'normal': 1.5,
      'relaxed': 1.675,
      'loose': 2,
    },
    WebkitFontSmoothing: {
      antialiased: 'antialiased',
      subpixelAntialiased: 'auto',
    },
    MozOsxFontSmoothing: {
      antialiased: 'grayscale',
      subpixelAntialiased: 'auto',
    },
    fontStyle: {
      italic: 'italic',
      notItalic: 'normal',
    },
    fontWeight: {
      thin: 100,
      extralight: 200,
      light: 300,
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      extrabold: 800,
      black: 900,
    },
    fontVariantNumeric: {
      normalNums: 'normal',
      ordinal: 'ordinal',
      zero: 'slashed-zero',
      liningNums: 'lining-nums',
      oldstyleNums: 'oldstyle-nums',
      proportionalNums: 'proportional-nums',
      tabularNums: 'tabular-nums',
      diagonalFractions: 'diagonal-fractions',
      stackedFractions: 'stacked-fractions',
    },
    letterSpacing: {
      tighter: '-0.05em',
      tight: '-0.025em',
      normal: '0em',
      wide: '0.025em',
      wider: '0.05em',
      widest: '0.1em',
    },
    listStyleType: ['none', 'disc', 'decimal'],
    listStylePosition: ['inside', 'outside'],
    textAlign: ['left', 'right', 'center', 'justify', 'start', 'end'],
    color: palette,
    textDecorationLine: {
      underline: 'underline',
      overline: 'overline',
      lineThrough: 'line-through',
      noUnderline: 'none',
    },
    textDecorationColor: palette,
    textDecorationStyle: ['solid', 'double', 'dotted', 'dashed', 'wavy'],
    textDecorationThickness: {
      auto: 'auto',
      fromFont: 'from-font',
      0: '0px',
      1: '1px',
      2: '2px',
      4: '4px',
      8: '8px',
    },
    textUnderlineOffset: {
      auto: 'auto',
      0: '0px',
      1: '1px',
      2: '2px',
      4: '4px',
      8: '8px',
    },
    textTransform: {
      uppercase: 'uppercase',
      lowercase: 'lowercase',
      capitalize: 'capitalize',
      normalCase: 'none',
    },
    textIndent: basicNumberSize,
    verticalAlign: {
      baseline: 'baseline',
      top: 'top',
      middle: 'middle',
      bottom: 'bottom',
      textTop: 'text-top',
      textBottom: 'text-bottom',
      sub: 'sub',
      super: 'super',
    },
    whiteSpace: {
      normal: 'normal',
      nowrap: 'nowrap',
      pre: 'pre',
      preLine: 'pre-line',
      preWrap: 'pre-wrap',
    },
    wordBreak: {
      normal: 'normal',
      words: 'break-word',
      all: 'break-all',
      breakKeep: 'keep-all',
    },
    content: ['none'],
  },
  shorthands: {
    textSize: ['fontSize', 'lineHeight'],
    textSmoothing: ['WebkitFontSmoothing', 'MozOsxFontSmoothing'],
    tracking: ['letterSpacing'],
    list: ['listStyleType'],
    indent: ['textIndent'],
    align: ['verticalAlign'],
    break: ['wordBreak'],
  },
})
